// Localizaciones reales de Madrid con carga ocultista/histórica.
// Las coordenadas (x, y) están en el sistema del SVG del mapa (0–800, 0–700)
// y son aproximadas: este no es un GPS, es un grabado.

export const MADRID_LOCATIONS = [
  {
    id: "debod",
    name: "Templo de Debod",
    district: "Príncipe Pío",
    x: 220, y: 280,
    type: "templo",
    short: "Templo egipcio reerigido sobre el solar del cuartel arrasado en julio del 36.",
    long: `Donado por Egipto en 1968 y reerigido en el Cerro del Príncipe Pío, sobre el solar exacto del cuartel de la Montaña asaltado el 19 de julio de 1936 y reducido a polvo el mismo día. La logia mantiene que el agua del estanque sube media línea las noches en que se cumple aniversario de cualquier 19. El sumidero no consta en planos municipales.`,
    encounter: "Un sacerdote de Amón mendiga monedas de cinco pesetas. Solo acepta las acuñadas antes de 1972.",
  },
  {
    id: "linares",
    name: "Palacio de Linares",
    district: "Cibeles",
    x: 470, y: 320,
    type: "palacio",
    short: "El fantasma de Raimundita aún hace ruidos en la sala neorrenacentista.",
    long: `Construido en 1873 por el marqués de Linares con plata extraída a su pesar de las minas de Linares. Casa de América desde 1992. Cinco veces se ha grabado en cinta magnetofónica la voz infantil de una niña diciendo 'mamá, mamá, mírame'. Los marqueses tuvieron una hija de la que no se sabe nada en los registros eclesiásticos del XIX. La logia conserva una transcripción.`,
    encounter: "Una niña pequeña con vestido del XIX te ofrece jugar al cucú-tras. Si aceptas, pierdes una hora real.",
  },
  {
    id: "siete-chimeneas",
    name: "Casa de las Siete Chimeneas",
    district: "Plaza del Rey",
    x: 460, y: 310,
    type: "palacio",
    short: "Elena, amante secreta de Felipe II, recorre el tejado en camisón blanco.",
    long: `Edificada hacia 1577 sobre la finca de un cortesano de Felipe II, hoy sede del Ministerio de Cultura. La leyenda dice que su primera moradora, Elena, fue asesinada y emparedada en una de las chimeneas tras un asunto regio nunca esclarecido. En el siglo XIX una obra encontró restos humanos y monedas de la época de Felipe II. La logia conserva uno de los reales de plata.`,
    encounter: "Una mujer en camisón te invita a contar las chimeneas. Hay siete. Si las cuentas dos veces, hay ocho.",
  },
  {
    id: "san-isidro",
    name: "Cementerio Sacramental de San Isidro",
    district: "Carabanchel",
    x: 280, y: 540,
    type: "cementerio",
    short: "Goya enterrado sin cabeza. Larra. Un panteón con la palabra 'paz' grabada 200 veces.",
    long: `Cementerio del XIX abierto en 1811 sobre la ermita de San Isidro. Aquí descansaron Goya (descabezado en su traslado), Larra (suicidado en 1837), Cánovas y la gran masonería madrileña del XIX. La logia ha localizado un panteón anónimo con la palabra 'paz' inscrita doscientas veces sin tachadura — coincidencia con el cuaderno de Godoy en París, signatura no probada.`,
    encounter: "Un sereno con farol del XIX te ofrece acompañarte a una tumba sin nombre. Aceptar es opción.",
  },
  {
    id: "almudena-cementerio",
    name: "Cementerio de la Almudena",
    district: "Este",
    x: 660, y: 380,
    type: "cementerio",
    short: "El cementerio mayor de Europa. Cuadrícula racional, panteones masones disimulados.",
    long: `Inaugurado en 1884 como Necrópolis del Este. Cinco millones de enterramientos. Los planos originales muestran cuatro cuadrantes y un eje central orientado al amanecer del solsticio. En el cuadrante segundo se conservan panteones de masones del XIX con simbología en clave: compás, escuadra, columnas truncadas. La logia los catalogó en 1972 antes de que el ayuntamiento limpiara fachadas.`,
    encounter: "Tres viudas en hilera te preguntan tu fecha de nacimiento. Si la dices, escupen al suelo y se van.",
  },
  {
    id: "observatorio",
    name: "Real Observatorio Astronómico",
    district: "Cerrillo de San Blas",
    x: 530, y: 410,
    type: "saber",
    short: "Templete neoclásico de Villanueva. Aquí Olivares consultaba Saturno por persona interpuesta.",
    long: `Fundado en 1790 por Carlos III, edificio de Juan de Villanueva. Aquí se instaló el primer círculo meridiano de España y se calcularon las efemérides oficiales hasta bien entrado el XX. Los archivos áulicos del Conde-Duque registran consultas indirectas sobre la posición de Saturno por mediación de un astrónomo flamenco llamado Ñ. Las efemérides oficiales no contemplan, por norma, demonios menores.`,
    encounter: "Un astrónomo con peluca te ofrece leer tu carta natal. Si le dices el año, te pide los minutos.",
  },
  {
    id: "claudio-coello",
    name: "Calle Claudio Coello, 104",
    district: "Salamanca",
    x: 580, y: 290,
    type: "memoria",
    short: "La ascensión del almirante Carrero Blanco. 20 de diciembre de 1973, 9:35.",
    long: `Calle del barrio de Salamanca donde el 20 de diciembre de 1973 ETA hizo estallar una carga subterránea bajo el Dodge 3700 del presidente del Gobierno, lanzándolo por encima del edificio de cinco plantas. El coche cayó en el patio de la iglesia jesuita de San Francisco de Borja. La logia mantiene la teoría órbita irregular en torno a Júpiter, perihelio cada once años aproximados.`,
    encounter: "Un almirante en uniforme te pregunta la hora. Solo acepta horas con minuto impar.",
  },
  {
    id: "moyano",
    name: "Cuesta de Moyano",
    district: "Atocha",
    x: 510, y: 470,
    type: "saber",
    short: "Casetas de libros viejos. Aquí Azaña encontró un Spinoza por seis reales.",
    long: `Treinta casetas de madera instaladas desde 1925 en cuesta junto al Real Jardín Botánico. Manuel Azaña fue cliente habitual antes del exilio y se llevó de aquí el Spinoza empolvado que cruzó el Pirineo. Los libreros tienen memoria larga: aún recuerdan al cliente Don Manuel y la última factura impagada de noviembre de 1936. La logia conserva una hoja de pedido.`,
    encounter: "Un librero ciego te recomienda exactamente el libro que querías esconder. Lo cobra a cuarenta euros.",
  },
  {
    id: "san-anton",
    name: "Iglesia de San Antonio de los Alemanes",
    district: "Malasaña",
    x: 410, y: 290,
    type: "templo",
    short: "Frescos del XVII en bóveda elíptica. Aún se sopla una vela invisible cada año.",
    long: `Iglesia barroca de 1624 con bóveda elíptica completamente cubierta de frescos. Fue templo del hospital alemán y desde el XVII celebra una misa nocturna en San Antón en la que, según la tradición, se apaga una vela del altar mayor sin causa atribuida. La logia ha medido la corriente de aire en esa zona y la ha registrado como nula durante el episodio.`,
    encounter: "Un cura jubilado te confiesa sin pedírselo. Te perdona pecados que no recordabas haber cometido.",
  },
  {
    id: "san-gines",
    name: "Pasadizo de San Ginés",
    district: "Sol",
    x: 410, y: 360,
    type: "memoria",
    short: "Chocolatería del XIX. Posada del Peine al lado. Aquí firmaba Cánovas sus pactos.",
    long: `Callejón medieval entre la calle del Arenal y la iglesia de San Ginés, con chocolatería abierta en 1894 y posada del Peine, hospedaje del XVII, en el otro extremo. La logia conserva que aquí Cánovas firmaba en servilleta los pactos del turnismo con Sagasta, generalmente a las tres de la madrugada y con dos churros como testigos.`,
    encounter: "Un camarero te trae un chocolate que no pediste. La cuenta lleva un nombre que no es el tuyo.",
  },
  {
    id: "plaza-villa",
    name: "Casa de Cisneros / Plaza de la Villa",
    district: "Centro",
    x: 380, y: 380,
    type: "palacio",
    short: "Plaza medieval. La Casa de Cisneros tiene cripta gótica con tres losas sin epitafio.",
    long: `Plaza medieval donde se reunía el Concejo Madrileño desde el XV. La Casa de Cisneros (1537), edificada por Benito Jiménez de Cisneros, sobrino del cardenal, conserva en su sótano una cripta gótica con tres losas sin epitafio. La leyenda local atribuye las losas a tres regidores del XVI fallecidos en circunstancias nunca explicadas. La logia tiene transcrita la versión de uno de los porteros, fechada en 1948.`,
    encounter: "Un escribano del XVII te pide testimonio sobre un pleito que se cerró hace 400 años. Si firmas, gana.",
  },
  {
    id: "plaza-oriente",
    name: "Plaza de Oriente / Cripta del Palacio",
    district: "Centro",
    x: 340, y: 340,
    type: "palacio",
    short: "Estatuas de reyes godos. Bajo el palacio, criptas con jesuitas y un alquimista.",
    long: `Plaza diseñada por José Bonaparte y rematada por Isabel II en 1844, con veinte estatuas de reyes góticos y prerromanos sobre pedestal. Bajo el Palacio Real, criptas con tumbas de jesuitas del XVII, una de las cuales (sin nombre) se asocia con un alquimista catalán cuya identidad permanece bajo secreto eclesiástico. La logia ha estado dos veces y no consta más que rumor.`,
    encounter: "Una estatua de rey godo se gira un grado cuando le das la espalda. No se mueve si la miras.",
  },
  {
    id: "almudena-cripta",
    name: "Cripta de la Almudena",
    district: "Centro",
    x: 330, y: 380,
    type: "templo",
    short: "Cripta neorrománica con 558 columnas. Tumba de la Marquesa de Squilache.",
    long: `Cripta de la Catedral de la Almudena, construida en 1911 antes que el templo superior, en estilo neorrománico con 558 columnas y veinte capillas privadas. En una de ellas reposa la Marquesa de Squilache (relacionada con el ministro de Carlos III del motín de 1766) y se cita la presencia de cinco placas anónimas atribuidas por la logia a personajes del Real Tribunal del Santo Oficio.`,
    encounter: "Una marquesa con abanico te pregunta si quieres heredar. Solo acepta sí o no, no admite duda.",
  },
];

export const LOCATION_TYPE_LABEL = {
  templo: "Templo",
  palacio: "Palacio",
  cementerio: "Cementerio",
  saber: "Saber",
  memoria: "Memoria",
};

export const LOCATION_TYPE_COLOR = {
  templo: "#5C1820",
  palacio: "#A88B3F",
  cementerio: "#1A1410",
  saber: "#3D5C1A",
  memoria: "#6E3015",
};
