// Localizaciones reales de Madrid con carga ocultista e histórica.
// Las coordenadas (lat, lng) son aproximadas: esto no es un GPS, es un grabado.

export const MADRID_LOCATIONS = [
  {
    id: "debod",
    lat: 40.424, lng: -3.7175,
    name: "Templo de Debod",
    district: "Príncipe Pío",
    x: 220, y: 280,
    type: "templo",
    short: "Templo egipcio reerigido sobre el solar del cuartel arrasado en julio del 36.",
    long: `Donado por Egipto en 1968 y vuelto a levantar piedra a piedra en el Cerro del Príncipe Pío, sobre el solar exacto del Cuartel de la Montaña asaltado el 19 de julio de 1936 y reducido a polvo aquel mismo día. La Logia sostiene —sin garantía notarial— que el agua del estanque asciende media línea las noches en que se cumple aniversario de cualquier 19. El sumidero del estanque no figura en ningún plano municipal vigente.`,
    encounter: "Un sacerdote de Amón mendiga monedas de cinco pesetas. No admite las acuñadas después de 1972.",
  },
  {
    id: "linares",
    lat: 40.419, lng: -3.6933,
    name: "Palacio de Linares",
    district: "Cibeles",
    x: 470, y: 320,
    type: "palacio",
    short: "El fantasma de Raimundita aún se hace oír en la sala neorrenacentista.",
    long: `Levantado en 1873 por el marqués de Linares con plata arrancada, a su pesar, a las minas que dieron nombre al título. Sede de Casa de América desde 1992. En cinco ocasiones se ha grabado en cinta magnetofónica una voz infantil que repite "mamá, mamá, mírame". Los marqueses tuvieron una hija de la que nada consta en los registros eclesiásticos del XIX; la Logia conserva una transcripción de la cinta y la signatura de un cura que se negó a firmarla.`,
    encounter: "Una niña con vestido decimonónico te invita a jugar al cucú-tras. Aceptar cuesta una hora de tu vida.",
  },
  {
    id: "siete-chimeneas",
    lat: 40.4202, lng: -3.6957,
    name: "Casa de las Siete Chimeneas",
    district: "Plaza del Rey",
    x: 460, y: 310,
    type: "palacio",
    short: "Elena, amante secreta de Felipe II, recorre el tejado en camisón blanco.",
    long: `Edificada hacia 1577 sobre la finca de un cortesano de Felipe II, hoy sede del Ministerio de Cultura. La tradición sostiene que su primera moradora, Elena, fue asesinada y emparedada en una de las chimeneas tras un asunto regio nunca esclarecido. En el siglo XIX, durante unas obras, aparecieron restos humanos y monedas de la época de Felipe II; la Logia conserva uno de aquellos reales de plata, custodiado en sobre lacrado.`,
    encounter: "Una mujer en camisón te pide que cuentes las chimeneas. Son siete. Si las cuentas dos veces, son ocho.",
  },
  {
    id: "san-isidro",
    lat: 40.3987, lng: -3.7277,
    name: "Cementerio Sacramental de San Isidro",
    district: "Carabanchel",
    x: 280, y: 540,
    type: "cementerio",
    short: "Goya, enterrado sin cabeza. Larra. Un panteón con la palabra «paz» grabada doscientas veces.",
    long: `Cementerio decimonónico abierto en 1811 sobre la ermita de San Isidro. Aquí descansaron Goya —descabezado durante uno de sus traslados—, Larra —suicidado en 1837—, Cánovas y buena parte de la masonería madrileña del XIX. La Logia ha localizado un panteón anónimo en cuya losa aparece grabada la palabra paz doscientas veces, sin tachadura ni firma. La coincidencia con el cuaderno parisino atribuido a Godoy se documenta en signatura aparte y aún no acreditada.`,
    encounter: "Un sereno con farol decimonónico se ofrece a guiarte hasta una tumba sin nombre. Aceptar es opción.",
  },
  {
    id: "almudena-cementerio",
    lat: 40.4219, lng: -3.6453,
    name: "Cementerio de la Almudena",
    district: "Este",
    x: 660, y: 380,
    type: "cementerio",
    short: "El cementerio mayor de Europa. Trazado racional; panteones masones disimulados.",
    long: `Inaugurado en 1884 como Necrópolis del Este. Cinco millones de enterramientos. Los planos originales muestran cuatro cuadrantes y un eje central orientado al amanecer del solsticio. En el segundo cuadrante perviven panteones de masones decimonónicos con simbología en clave: compás, escuadra, columna truncada. La Logia los catalogó en 1972, justo antes de que el Ayuntamiento mandara limpiar las fachadas.`,
    encounter: "Tres viudas en fila te preguntan la fecha en que naciste. Si la dices, escupen al suelo y se marchan sin volverse.",
  },
  {
    id: "observatorio",
    lat: 40.4087, lng: -3.6888,
    name: "Real Observatorio Astronómico",
    district: "Cerrillo de San Blas",
    x: 530, y: 410,
    type: "saber",
    short: "Templete neoclásico de Villanueva. Aquí Olivares consultaba a Saturno por persona interpuesta.",
    long: `Fundado en 1790 por Carlos III en edificio de Juan de Villanueva. Aquí se instaló el primer círculo meridiano de España y se calcularon las efemérides oficiales hasta bien entrado el siglo XX. Los archivos áulicos del Conde-Duque registran consultas indirectas sobre la posición de Saturno, encargadas a un astrónomo flamenco al que solo se nombra con la inicial Ñ. Las efemérides oficiales no contemplan, por norma, los demonios menores.`,
    encounter: "Un astrónomo empolvado se ofrece a leerte la carta natal. Si le das el año, te exige también los minutos.",
  },
  {
    id: "claudio-coello",
    lat: 40.4315, lng: -3.6856,
    name: "Calle Claudio Coello, 104",
    district: "Salamanca",
    x: 580, y: 290,
    type: "memoria",
    short: "La ascensión del almirante Carrero Blanco. 20 de diciembre de 1973, a las 09:35.",
    long: `Calle del barrio de Salamanca donde, el 20 de diciembre de 1973, ETA hizo estallar una carga subterránea bajo el Dodge 3700 del presidente del Gobierno, lanzándolo por encima de un edificio de cinco plantas. El coche cayó en el patio interior de la iglesia jesuita de San Francisco de Borja. La Logia sostiene, a título no concluyente, la tesis de una órbita irregular en torno a Júpiter con perihelio aproximadamente cada once años.`,
    encounter: "Un almirante uniformado te pregunta la hora. Solo acepta horas cuyo minuto sea impar.",
  },
  {
    id: "moyano",
    lat: 40.4108, lng: -3.6898,
    name: "Cuesta de Moyano",
    district: "Atocha",
    x: 510, y: 470,
    type: "saber",
    short: "Casetas de libros viejos. Aquí Azaña encontró un Spinoza por seis reales.",
    long: `Treinta casetas de madera instaladas desde 1925 en la cuesta que limita con el Real Jardín Botánico. Manuel Azaña fue cliente asiduo antes del exilio y se llevó de aquí el Spinoza empolvado que cruzaría con él los Pirineos. Los libreros tienen memoria larga: aún recuerdan a Don Manuel y la última factura impagada, fechada en noviembre de 1936. La Logia conserva una hoja de pedido sin firmar.`,
    encounter: "Un librero ciego te ofrece, exacto, el libro que pensabas esconder. Lo tasa en cuarenta euros, ni uno menos.",
  },
  {
    id: "san-anton",
    lat: 40.4259, lng: -3.7016,
    name: "Iglesia de San Antonio de los Alemanes",
    district: "Malasaña",
    x: 410, y: 290,
    type: "templo",
    short: "Frescos del XVII en bóveda elíptica. Cada año se apaga una vela invisible.",
    long: `Iglesia barroca de 1624 con bóveda elíptica enteramente cubierta de frescos. Templo del antiguo hospital alemán, celebra desde el siglo XVII una misa nocturna en San Antón durante la cual, según tradición, se apaga una vela del altar mayor sin causa atribuible. La Logia midió la corriente de aire en esa zona durante el episodio y la registró como nula a efectos prácticos.`,
    encounter: "Un cura jubilado te confiesa sin que lo pidas. Te absuelve de pecados que no recordabas haber cometido.",
  },
  {
    id: "san-gines",
    lat: 40.4176, lng: -3.7064,
    name: "Pasadizo de San Ginés",
    district: "Sol",
    x: 410, y: 360,
    type: "memoria",
    short: "Chocolatería decimonónica. Posada del Peine al lado. Aquí firmaba Cánovas sus pactos.",
    long: `Callejón medieval entre la calle del Arenal y la iglesia de San Ginés, con chocolatería abierta en 1894 y la posada del Peine —hospedaje del XVII— en el extremo opuesto. La Logia conserva memoria de que aquí Cánovas firmaba sobre servilleta los pactos del turnismo con Sagasta, por lo común hacia las tres de la madrugada y con dos churros por toda escolta.`,
    encounter: "Un camarero te trae un chocolate que no has pedido. La cuenta sale a nombre de otro, parecido al tuyo.",
  },
  {
    id: "plaza-villa",
    lat: 40.4152, lng: -3.7104,
    name: "Casa de Cisneros · Plaza de la Villa",
    district: "Centro",
    x: 380, y: 380,
    type: "palacio",
    short: "Plaza medieval. La Casa de Cisneros guarda una cripta gótica con tres losas sin epitafio.",
    long: `Plaza medieval en que se reunía el Concejo Madrileño desde el siglo XV. La Casa de Cisneros, edificada en 1537 por Benito Jiménez de Cisneros —sobrino del cardenal—, conserva en su sótano una cripta gótica con tres losas sin epitafio. La tradición local atribuye las losas a tres regidores del XVI fallecidos en circunstancias nunca esclarecidas. La Logia conserva una transcripción de la versión que dio uno de los porteros, fechada en 1948.`,
    encounter: "Un escribano del XVII te pide testimonio sobre un pleito cerrado hace cuatrocientos años. Si firmas, lo gana.",
  },
  {
    id: "plaza-oriente",
    lat: 40.4184, lng: -3.7123,
    name: "Plaza de Oriente · Cripta del Palacio",
    district: "Centro",
    x: 340, y: 340,
    type: "palacio",
    short: "Estatuas de reyes godos. Bajo el palacio, criptas con jesuitas y un alquimista.",
    long: `Plaza diseñada por José Bonaparte y completada por Isabel II en 1844, con veinte estatuas de reyes góticos y prerromanos sobre pedestal. Bajo el Palacio Real se conservan criptas con tumbas de jesuitas del XVII, una de las cuales —sin nombre— se asocia con un alquimista catalán cuya identidad permanece bajo secreto eclesiástico. La Logia ha llegado hasta allí en dos ocasiones; no consta otra cosa que rumor.`,
    encounter: "Una estatua de rey godo gira un grado cuando le das la espalda. No se mueve mientras la miras.",
  },
  {
    id: "almudena-cripta",
    lat: 40.4138, lng: -3.7143,
    name: "Cripta de la Almudena",
    district: "Centro",
    x: 330, y: 380,
    type: "templo",
    short: "Cripta neorrománica con 558 columnas. Tumba de la marquesa de Squilache.",
    long: `Cripta de la Catedral de la Almudena, levantada en 1911 antes que el templo superior, en estilo neorrománico, con 558 columnas y veinte capillas privadas. En una de ellas reposa la marquesa de Squilache —emparentada con el ministro de Carlos III caído en el motín de 1766— y se mencionan cinco placas anónimas que la Logia atribuye a personajes del Real Tribunal del Santo Oficio.`,
    encounter: "Una marquesa con abanico te pregunta si quieres heredar. Solo admite un sí o un no; la duda la ofende.",
  },
  {
    id: "congreso",
    lat: 40.4159, lng: -3.6971,
    name: "Congreso de los Diputados",
    district: "Cortes",
    x: 430, y: 395,
    type: "poder",
    short: "Carrera de San Jerónimo, 36. Los pasillos tienen memoria de mil votaciones.",
    long: `Sede del poder legislativo desde 1850. Los pasillos de mármol tienen memoria de mil votaciones y de otras tantas traiciones. El diputado que sale a fumar al patio y el que vuelve no siempre son la misma persona. En el bar de la Cámara se ha decidido más que en el hemiciclo. Las comisiones de las nueve de la mañana y las conversaciones de las once de la noche son, a efectos prácticos, legislaturas distintas.`,
    encounter: "Un portavoz sin grupo te aborda en los pasillos. Tiene cuatro escaños y ninguna prisa.",
  },
  {
    id: "sede-partido",
    lat: 40.4258, lng: -3.6897,
    name: "Sede del Partido",
    district: "Almagro",
    x: 510, y: 275,
    type: "poder",
    short: "Despacho con tres sillones. El que importa siempre está ocupado.",
    long: `En esta sala se ganan y se pierden primarias, se redactan comunicados y se decide quién va en la lista. El poder real no está en el hemiciclo; está aquí, a las diez de la noche con el teléfono descolgado. El secretario de organización lleva tres semanas sin salir antes de las once. Las listas autonómicas siguen abiertas. La cafetera lleva encendida desde las siete de la mañana del lunes pasado.`,
    encounter: "El secretario de organización tiene la lista encima de la mesa. Faltan seis nombres.",
  },
];

export const LOCATION_TYPE_LABEL = {
  templo: "Templo",
  palacio: "Palacio",
  cementerio: "Cementerio",
  saber: "Saber",
  memoria: "Memoria",
  poder: "Poder",
};

export const LOCATION_TYPE_COLOR = {
  templo: "#5C1820",
  palacio: "#A88B3F",
  cementerio: "#1A1410",
  saber: "#3D5C1A",
  memoria: "#6E3015",
  poder: "#3F5469",
};
