export const NPC_EVENTS = [
  {
    id: "baron-territorial",
    name: "Barón territorial",
    flavor: "Te exige cerrar una lista autonómica a última hora.",
    type: "politico",
    test: "carisma",
    difficulty: 9,
    success: { influence: 2, threat: 0, text: "Alineas al aparato sin romper alianzas." },
    fail: { influence: 0, threat: 1, text: "Filtración interna y titulares hostiles." },
  },
  {
    id: "sindicato",
    name: "Enlace sindical",
    flavor: "Amenazan con rueda de prensa si no cedes en presupuesto.",
    type: "politico",
    test: "voluntad",
    difficulty: 8,
    success: { influence: 2, threat: 0, text: "Pactas calendario y desactivas huelga." },
    fail: { influence: 1, threat: 1, text: "Aceptan a medias y te desgastan en medios." },
  },
  {
    id: "lobby-energia",
    name: "Lobby energético",
    flavor: "Ofrecen apoyo discreto a cambio de una enmienda.",
    type: "politico",
    test: "perspicacia",
    difficulty: 10,
    success: { influence: 3, threat: 0, text: "Negocias sin dejar rastro comprometedor." },
    fail: { influence: 0, threat: 2, text: "Quedas expuesto en comisión de investigación." },
  },
];
