// 90 preguntas. Se barajan al iniciar el quiz y se cogen N según modo.
// Cada opción está indexada 0..3 — el matcher hace referencia a opciones por índice.

export const QUESTION_BANK = [
  { id: 1, text: "Al firmar un pacto importante, prefieres hacerlo...", options: ["A medianoche, sin testigos", "En despacho oficial con cámaras", "En sobre cerrado, por mensajero", "En voz alta, ante los míos"] },
  { id: 2, text: "El número que más te persigue es el...", options: ["3", "7", "13", "Ninguno, las cifras no me dicen nada"] },
  { id: 3, text: "Tu signo zodiacal corresponde a...", options: ["Fuego (Aries, Leo, Sagitario)", "Tierra (Tauro, Virgo, Capricornio)", "Aire (Géminis, Libra, Acuario)", "Agua (Cáncer, Escorpio, Piscis)"] },
  { id: 4, text: "Si tuvieras que esconder un secreto de Estado, lo guardarías...", options: ["En caja fuerte con código", "Memorizado, sin papel", "En la conciencia de un confesor", "En un USB enterrado en el campo"] },
  { id: 5, text: "Tu relación con el Vaticano...", options: ["Cordial y útil", "Distante pero respetuosa", "Hostil, pero callada", "Complicada: hay deudas antiguas"] },
  { id: 6, text: "Si te ofrecen entrar en una logia masónica...", options: ["Acepto si me convienen los grados", "Ya pertenezco a una", "Rechazo, son cosas raras", "Rechazo, pero monto la mía propia"] },
  { id: 7, text: "El símbolo que pondrías en tu sello personal sería...", options: ["Un águila", "Una corona", "Un puño cerrado", "Una llave"] },
  { id: 8, text: "Antes de una rueda de prensa difícil...", options: ["Rezo lo que sea, sirve", "Repaso el guion una última vez", "Bebo algo fuerte", "Toco un objeto talismán"] },
  { id: 9, text: "'Todo está atado y bien atado' te parece...", options: ["Una promesa que se cumple sola", "Una ingenuidad", "Un programa de gobierno serio", "Una maldición operativa"] },
  { id: 10, text: "Si hay eclipse el día de una votación crucial...", options: ["Señal favorable", "Señal nefasta, me cuido", "No miro al cielo, miro a las urnas", "Señal de que el rival está acabado"] },
  { id: 11, text: "Tu sustancia ritual de despacho...", options: ["Café muy cargado", "Tabaco rubio sin filtro", "Whisky escocés", "Manzanilla y pan tostado"] },
  { id: 12, text: "¿Has firmado algún pacto del que te arrepientas?", options: ["Sí, varios", "Uno, y aún pago consecuencias", "Ninguno, todos firmes", "Nunca firmo nada por escrito"] },
  { id: 13, text: "Cuando un correligionario te apuñala por la espalda...", options: ["Lo entierro políticamente", "Sonrío en público, lo arruino en privado", "Le sonrío y espero a que se equivoque", "Renuncio antes que volverlo a mirar"] },
  { id: 14, text: "La España auténtica para ti está en...", options: ["Castilla profunda", "La costa mediterránea", "El País Vasco y Navarra", "Madrid capital y nada más"] },
  { id: 15, text: "Si te aparece un mendigo en sueños tres noches seguidas...", options: ["Es presagio, hay que actuar", "Es estrés, lo ignoro", "Es un aviso del partido", "Soy yo en el futuro"] },
  { id: 16, text: "Tu coche oficial preferido sería...", options: ["Audi negro discreto", "Mercedes con banderines", "Falcon a cualquier sitio", "AVE en clase preferente"] },
  { id: 17, text: "La traición a la patria se castiga con...", options: ["Muerte civil", "Exilio dorado", "Olvido absoluto", "Una columna en un diario"] },
  { id: 18, text: "Tu día preferido para una purga interna...", options: ["Lunes, todos frescos", "Viernes por la tarde", "Domingo, sale en lunes", "Cualquiera; no se planean"] },
  { id: 19, text: "Si encuentras una urna electoral abandonada...", options: ["La devuelvo intacta", "La abro, a ver qué hay", "La quemo, no la he visto", "Pido instrucciones por canal trasero"] },
  { id: 20, text: "El Opus Dei...", options: ["Es útil, hay que llevarse bien", "Es peligrosísimo", "Una herramienta más entre otras", "No existe como tal"] },
  { id: 21, text: "Si llevases escapulario, sería de...", options: ["La Virgen de la Almudena", "La Virgen del Pilar", "Sant Jordi", "No llevaría ninguno"] },
  { id: 22, text: "Tu manera de echar a alguien del gobierno...", options: ["Comida tranquila, sin gritos", "Filtración en un diario amigo", "Carta manuscrita", "Que se entere por la televisión"] },
  { id: 23, text: "El tarot como herramienta política...", options: ["Lo consulto en serio", "Es entretenimiento", "Es satánico", "Mi gabinete lo consulta por mí"] },
  { id: 24, text: "¿Has hablado alguna vez con un muerto?", options: ["Sí, varias, y me ha respondido", "Sí, pero sin respuesta", "No, qué va", "Soy yo quien les habla; callados ellos"] },
  { id: 25, text: "Tu peor enemigo está en...", options: ["Tu propio partido", "La oposición", "La prensa", "Tu familia"] },
  { id: 26, text: "Libro prohibido en tu mesilla...", options: ["Maquiavelo", "Gracián", "Una Biblia subrayada", "Las memorias de un enemigo"] },
  { id: 27, text: "El verbo que mejor te define negociando...", options: ["Esperar", "Prometer", "Amenazar", "Confundir"] },
  { id: 28, text: "El olor de los pasillos del Congreso te resulta...", options: ["Hogar", "Insoportable", "Indiferente", "Como el de una sacristía"] },
  { id: 29, text: "Tu relación con el ejército...", options: ["Estrecha y antigua", "Correcta y distante", "Tensa", "Nunca te has metido ahí"] },
  { id: 30, text: "Cuando te llaman dictador en redes...", options: ["Me lo tomo a risa", "Me indigno", "Lo bloqueo sin más", "Lo tomo como un ascenso"] },
  { id: 31, text: "El alma del PSOE es...", options: ["Andaluza", "Vasca, de Indalecio Prieto", "Sevillana de los aparatchik", "No tiene alma, tiene aparato"] },
  { id: 32, text: "El alma del PP es...", options: ["Gallega y prudente", "Madrileña y de barra", "Vasco-conservadora", "No tiene alma, tiene cuentas"] },
  { id: 33, text: "La masonería del XIX en España fue...", options: ["Decisiva en todo", "Anecdótica", "Una excusa franquista", "Una pena que se extinguiera"] },
  { id: 34, text: "Tu noche ideal de campaña es...", options: ["Mitin lleno y bocadillo después", "Tertulia hasta la madrugada", "Cena solo, repasando notas", "Discoteca con escolta"] },
  { id: 35, text: "Si vieses un OVNI en visita oficial...", options: ["Lo digo y que me callen", "Lo callo, qué remedio", "Conozco a quien lo vio", "Solo veo OVNIs metafóricos"] },
  { id: 36, text: "Si un periodista te chantajea con una foto vieja...", options: ["Le explico que la foto soy yo, con orgullo", "Niego en redondo", "Pago una vez y mato la fuente", "Publico yo otra suya"] },
  { id: 37, text: "Tu animal espiritual político...", options: ["Lobo ibérico", "Toro de Osborne", "Búho", "Cuervo"] },
  { id: 38, text: "Las purgas de tu propio partido las gestionas...", options: ["Frías y públicas", "Por canal trasero", "Las delega mi número dos", "No purgo: dejo morir"] },
  { id: 39, text: "El cuerpo de Franco...", options: ["Donde estaba, mejor", "Donde está ahora, correcto", "En el mar", "En su casa, con su familia"] },
  { id: 40, text: "Si pudieras presidir el Gobierno un día sin consecuencias...", options: ["Firmo un decretazo histórico", "Doy un discurso para los siglos", "Despido a media plantilla", "Lo gozo en silencio, sin firmar nada"] },
  { id: 41, text: "Hablas otra lengua del Estado...", options: ["Sí, y la uso", "Sí, pero no la uso", "No, ni falta", "No, pero me gustaría"] },
  { id: 42, text: "Si jurases el cargo, lo harías sobre...", options: ["La Constitución, a secas", "La Biblia", "Un libro de mi elección", "Por imperativo legal y nada más"] },
  { id: 43, text: "Pides un favor a otro político...", options: ["Cara a cara, sin testigos", "Carta manuscrita", "Por intermediario", "Llamada nocturna"] },
  { id: 44, text: "Si se te apareciese el espíritu de Largo Caballero...", options: ["Le pido que se calle, ya hizo bastante", "Le abro una cerveza", "Lo grabo, lo subo", "Le confieso mis dudas"] },
  { id: 45, text: "El presidente del Gobierno debe parecerse a...", options: ["Un notario", "Un cura", "Un sargento", "Un escritor"] },
  { id: 46, text: "Cuando te dejan fuera de la foto importante...", options: ["Hago otra desde fuera", "Monto otra mejor", "Me callo y aguardo", "Lo perdono al cabo de los años"] },
  { id: 47, text: "La España de las regiones es...", options: ["Una bendición", "Un dolor de cabeza", "Un experimento fallido", "El futuro inevitable"] },
  { id: 48, text: "Tu refugio cuando todo va mal...", options: ["Una iglesia vacía", "Una librería de viejo", "Un bar de toda la vida", "Mi casa, con la familia"] },
  { id: 49, text: "Si tuvieras que ungir a tu sucesor, lo harías con...", options: ["Aceite de oliva virgen extra", "Un apretón de manos en público", "Una carta a abrir tras tu muerte", "Nada; que se las arregle"] },
  { id: 50, text: "Te dicen que tu adversario consulta a un vidente...", options: ["Yo consulto al mío", "Me río abiertamente", "Investigo al vidente", "Lo contrato yo también"] },
  { id: 51, text: "¿Has tenido un sueño profético?", options: ["Sí, y se cumplió", "Sí, y lo provoqué yo mismo", "No creo en eso", "Sí, y no lo cuento a nadie"] },
  { id: 52, text: "Tu palabra favorita en castellano oficial...", options: ["Concordia", "Mandato", "Lealtad", "Estabilidad"] },
  { id: 53, text: "Si te ofrecen un cargo en Bruselas...", options: ["Lo cojo a la primera", "Lo medito mucho", "Solo si no hay alternativa aquí", "Nunca: mi sitio es España"] },
  { id: 54, text: "Tu manera de tomar el café...", options: ["Solo, sin azúcar", "Cortado con sacarina", "Manchado con leche caliente", "Doble americano por la mañana"] },
  { id: 55, text: "El mejor presidente que ha tenido España fue...", options: ["Suárez", "Felipe González", "Aznar", "Otro o ninguno"] },
  { id: 56, text: "Te dicen que un ministro tuyo se ha vendido...", options: ["Lo expulso ese mismo día", "Lo investigo en silencio", "Lo asciendo para tenerlo cerca", "Lo niego en público"] },
  { id: 57, text: "La 'razón de Estado'...", options: ["La entiendo y la aplico", "Es excusa cobarde", "El ABC de gobernar", "Solo en emergencia"] },
  { id: 58, text: "Si fundases un partido nuevo, su color sería...", options: ["Verde oscuro", "Morado", "Azul agua", "Negro"] },
  { id: 59, text: "Tu relación con los toros...", options: ["Cultura nacional, defenderla", "Tradición que respeto sin practicar", "Crueldad inadmisible", "Indiferente"] },
  { id: 60, text: "Cuando la prensa pega fuerte...", options: ["Llamo al director", "Demando", "Aguanto y espero", "Compro un medio"] },
  { id: 61, text: "¿Has consultado la cábala?", options: ["Sí, con gente seria", "Sí, en broma", "No, pero leo astrología", "No, jamás"] },
  { id: 62, text: "Tu hora preferida para anuncios difíciles...", options: ["Viernes por la tarde", "Lunes por la mañana", "Domingo a última hora", "Cualquiera, sin esconderme"] },
  { id: 63, text: "'No es no' en política significa...", options: ["Postura firme", "Postura provisional", "Trampa retórica", "Algo que dije y no debí"] },
  { id: 64, text: "Te ofrecen escaño europeo retirándote de la política nacional...", options: ["Acepto, es jubilación digna", "Lo cojo y vuelvo", "Lo rechazo por dignidad", "Lo negocio al alza"] },
  { id: 65, text: "Tu obra de teatro favorita sobre el poder...", options: ["Macbeth", "Fuenteovejuna", "La vida es sueño", "Las brujas de Salem"] },
  { id: 66, text: "Si tu cara apareciese en una vela votiva...", options: ["Me siento halagado", "La demando", "Compro todo el stock", "Es señal divina"] },
  { id: 67, text: "La mejor forma de quitarse de encima a un rival...", options: ["Promoverlo a algo lejano", "Esperar a que se equivoque", "Provocarle el error", "Pactar y dividirse el botín"] },
  { id: 68, text: "Tu lugar de retiro tras la política...", options: ["Una finca con olivos", "Apartamento en Madrid", "Casa en la costa", "Una embajada cómoda"] },
  { id: 69, text: "Si descubrieras una sociedad secreta dentro de tu partido...", options: ["Me afilio", "La denuncio", "La estudio antes de decidir", "Era yo el fundador"] },
  { id: 70, text: "Tu rito antes de un debate de investidura...", options: ["Misa privada", "Repaso con mi equipo", "Comer fuerte y siesta", "No tengo rito"] },
  { id: 71, text: "Si pudieras hablar con la Pasionaria un cuarto de hora...", options: ["Le pediría consejo", "Le diría que se equivocó", "La grabaría sin permiso", "Le ofrecería un trato"] },
  { id: 72, text: "Expedientes de tu vida que no enseñarías a tu madre...", options: ["Ninguno, soy un libro abierto", "Dos o tres", "Demasiados", "Los he quemado todos"] },
  { id: 73, text: "Tu villano favorito de la historia de España...", options: ["Godoy", "Carrero Blanco", "El Conde-Duque de Olivares", "Otro"] },
  { id: 74, text: "Cuando te llaman a Zarzuela...", options: ["Voy con discurso preparado", "Voy a escuchar", "Voy con condiciones", "Espero a que vengan ellos a mí"] },
  { id: 75, text: "Si en Moncloa se te apareciese un demonio menor...", options: ["Lo escucho, a ver qué propone", "Lo bendigo en latín", "Lo bloqueo en redes", "Lo nombro asesor sin sueldo"] },
  { id: 76, text: "Tu defecto más confesable...", options: ["Controlador", "Impaciente", "Rencoroso", "Demasiado leal"] },
  { id: 77, text: "El sitio de España con más energía oscura...", options: ["El Valle de los Caídos", "El Congreso", "El Banco de España", "Toledo"] },
  { id: 78, text: "Si tuvieras que esconder un cadáver político...", options: ["Lo entierro en una comisión", "Lo cuelgo de un escándalo ajeno", "Lo dejo a la vista, sin mirar", "No hay cadáveres en mi historial"] },
  { id: 79, text: "Tu relación con la prensa rosa...", options: ["Inexistente", "Tensa", "Útil", "Soy yo quien filtra"] },
  { id: 80, text: "El último libro que leíste de un tirón...", options: ["Una biografía política", "Un thriller", "Un ensayo de filosofía", "Hace años que no leo así"] },
  { id: 81, text: "Si te ofrecen pacto con el diablo a cambio del CGPJ...", options: ["Firmo sin leer", "Negocio cláusulas", "Rechazo: mi alma no se vende", "Ya lo firmé hace años"] },
  { id: 82, text: "Tu manera de saludar a la oposición...", options: ["Cordial y vacío", "Frío y digno", "Burlón", "Caluroso, son colegas de oficio"] },
  { id: 83, text: "Cuando un cura te recibe en privado...", options: ["Hablo de mi alma", "Hablo de política", "Hablo de mi familia", "Lo grabo discretamente"] },
  { id: 84, text: "Tu modo de gestionar a tu vicepresidente...", options: ["Lo neutralizo en silencio", "Le doy carrete y luego lo recojo", "Lo escucho de verdad", "Rival permanente"] },
  { id: 85, text: "Si rezaras a un santo político...", options: ["Sant Jordi", "Santa Teresa", "San Pelayo", "Cristo de la Buena Muerte"] },
  { id: 86, text: "Tu modo de dormir antes de una crisis...", options: ["Profundo, soy bestia", "Liviano, oigo todo", "Con somníferos", "No duermo: repaso"] },
  { id: 87, text: "El amor en política...", options: ["Debilidad", "Necesario", "Disimulable", "Lo he visto destruir gobiernos"] },
  { id: 88, text: "Si tuvieras una sola virtud sobrenatural...", options: ["Detectar mentira", "Imponer obediencia con la mirada", "Saber el día de mi muerte", "Hablar con los muertos"] },
  { id: 89, text: "Tu último pensamiento al ser derrotado en las urnas...", options: ["Volveré", "Era esperable", "Esto se ha amañado", "Por fin"] },
  { id: 90, text: "Al final de tu carrera, lo que quieres es que digan que fuiste...", options: ["Honrado", "Eficaz", "Necesario", "Inolvidable"] },
];
